### ISSUE TITLE
Teasers suck!

### ISSUE THREAD

**Issue by sebastianludwig** [jlnr/SansFonts#1]
:nose:

**Comment by jlnr** [comment]
Fixed. Time to install the El Capitan GM, because I cannot link to my iOS 9 app yet :(

**Comment by jlnr** [comment]
Only took Apple two weeks :)

https://itunes.apple.com/us/app/sans-fonts/id1037531461?mt=8

So much for being on the App Store on day 1. Let's see if I'll be more lucky on tvOS.

**Comment by sebastianludwig** [comment]
:+1: Now all I need is an iOS 9 device...
