### ISSUE TITLE
GSMArena is borked

### ISSUE THREAD

**Issue by jlnr** [jlnr/SansFonts#10]
![gsmarena](https://cloud.githubusercontent.com/assets/70772/11544173/bd157a38-9940-11e5-8700-471c2e1f850f.png)

**Comment by pocketarc** [comment]
Just for future reference, the URL is: http://st.gsmarena.com/vv/assets8/fonts/gsmarena.woff

If I have a bit of free time I'm going to try and sort out PRs for all the issues just to make sure they're all closed off. I love SansFonts. :D

**Comment by jlnr** [comment]
Thanks, and glad to hear that! :)
