### ISSUE TITLE
localhost and *.dev white-listing

### ISSUE THREAD

**Issue by pocketarc** [jlnr/SansFonts#35]
Would you be willing to white-list local development URLs? I've been working on a couple of projects where not having these white-listed means I have to keep turning off Sans Fonts in order to see the websites as they would be for most people. In local development environments Sans Fonts doesn't affect anything since there's no network latency to worry about. 

For localhost, adding to the `unless-domain` at the start of the blocker list would do it, and for *.dev we'd probably need a URL filter with "ignore-previous-rules". If it's something you're interested in, I'll write a PR for it as soon as I get a chance to.

**Comment by jlnr** [comment]
Good idea, would gladly accept a Pull Request.
