### ISSUE TITLE
apple.com looks like crap since switching to "SF"

### ISSUE THREAD

**Issue by jlnr** [jlnr/SansFonts#49]
![apple](https://cloud.githubusercontent.com/assets/70772/22423310/f6b64350-e72b-11e6-867f-8c058cf51739.png)

**Comment by sebastianludwig** [comment]
Also blocking "SF Pro Icons" might fix it (if that's possible somehow). At least if I remove that from the CSS, it looks fine again.

**Comment by jlnr** [comment]
Ah, I see. I have excluded `*icon*` fonts because most pages only use them for icons, but Apple decided to use it in their global font stack. With SF Pro blocked, everything defaults to SF Pro Icons, and for some reason, that font has ginormous whitespace. That sounds like a dumb idea on Apple's part.

It also earned Sans Fonts its first negative App Store review 🥇
